### ISSUE TITLE
InvalidRequestError

### ISSUE THREAD

**Issue by naiyouweibaomihua** [JusticeRage/Gepetto#34]
hey,guys,how to fix this error？my openai version = 1.24.0

`Request to davinci-003 sent...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:/sail/Program/windows Reverse/Disassemblers/ida/IDA_Pro_7.7/plugins/gepetto.py", line 211, in query_model
    response = openai.Completion.create(
  File "D:\sail\Program\windows Reverse\Disassemblers\ida\IDA_Pro_7.7\python38\lib\site-packages\openai\lib\_old_api.py", line 39, in __call__
    raise APIRemovedInV1(symbol=self._symbol)
openai.lib._old_api.APIRemovedInV1: 

You tried to access openai.Completion, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "D:/sail/Program/windows Reverse/Disassemblers/ida/IDA_Pro_7.7/plugins/gepetto.py", line 222, in query_model
    except openai.InvalidRequestError as e:
AttributeError: module 'openai' has no attribute 'InvalidRequestError'`

**Comment by JusticeRage** [comment]
Hi! First of all, the `davinci-003` model is quite old and not used by Gepetto anymore. Are you using the last version?
In more recent releases, Gepetto was also updated to use the new OpenAI API so this should fix your issue.
